### ISSUE TITLE
ddc file missing

### ISSUE THREAD

**Issue by foer** [melvyn2/intel-bt-fw-imgextract#1]
First of all: Thank you for sharing your work!
I'm not really familiar with this stuff and tried hours understanding what I have to do beginning in how to compile a rust binary, how to use a disassembler,...

I now managed to get the right image. I have a pci variant of the bluetooth chip. Bluetooth is working now! There is but an error left that there is a ddc-File missing. Do you know how to find and get this? 
Thanks

**Comment by melvyn2** [comment]
Hi,
The ddc file is optional according to `btintel.c`: https://github.com/torvalds/linux/blob/v6.12-rc3/drivers/bluetooth/btintel.c#L2796-L2797
If bluetooth is working as expected then it shouldn't be an issue. Let me know if not, though there's probably not much I can do.
